package recordManager;

/**
* recordManager/RecordManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from recordManager.idl
* Tuesday, June 5, 2018 11:40:46 o'clock PM EDT
*/

public final class RecordManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public recordManager.RecordManager value = null;

  public RecordManagerHolder ()
  {
  }

  public RecordManagerHolder (recordManager.RecordManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = recordManager.RecordManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    recordManager.RecordManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return recordManager.RecordManagerHelper.type ();
  }

}
