package recordManager;


/**
* recordManager/RecordManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from recordManager.idl
* Tuesday, June 5, 2018 11:40:46 o'clock PM EDT
*/

public interface RecordManager extends RecordManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RecordManager
