package recordManager;


/**
* recordManager/RecordManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from recordManager.idl
* Tuesday, June 5, 2018 11:40:46 o'clock PM EDT
*/

public abstract class RecordManagerPOA extends org.omg.PortableServer.Servant
 implements recordManager.RecordManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getCount", new java.lang.Integer (2));
    _methods.put ("serverGetCount", new java.lang.Integer (3));
    _methods.put ("editRecord", new java.lang.Integer (4));
    _methods.put ("transferRecord", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // recordManager/RecordManager/createTRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String Location = in.read_string ();
         String $result = null;
         $result = this.createTRecord (managerID, firstName, lastName, address, phone, specialization, Location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // recordManager/RecordManager/createSRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String courseRegesitered = in.read_string ();
         String status = in.read_string ();
         String statusDate = in.read_string ();
         String $result = null;
         $result = this.createSRecord (managerID, firstName, lastName, courseRegesitered, status, statusDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // recordManager/RecordManager/getCount
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.getCount (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // recordManager/RecordManager/serverGetCount
       {
         int $result = (int)0;
         $result = this.serverGetCount ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // recordManager/RecordManager/editRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editRecord (managerID, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // recordManager/RecordManager/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteServerName = in.read_string ();
         String $result = null;
         $result = this.transferRecord (managerID, recordID, remoteServerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:recordManager/RecordManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RecordManager _this() 
  {
    return RecordManagerHelper.narrow(
    super._this_object());
  }

  public RecordManager _this(org.omg.CORBA.ORB orb) 
  {
    return RecordManagerHelper.narrow(
    super._this_object(orb));
  }


} // class RecordManagerPOA
